#ifndef __ASM_ARCH_INFOMAX_IRQS_9868_H
#define __ASM_ARCH_INFOMAX_IRQS_9868_H

/*
 * 0-15:  STI/SGI (software triggered/generated interrupts)
 * 16-31: PPI (private peripheral interrupts)
 * 32+:   SPI (shared peripheral interrupts)
 */

#define IRQ_RESERVED			(32)
#define INT_CODA				(IRQ_RESERVED + 0)
#define INT_JPEG				(IRQ_RESERVED + 1)
#define INT_PING_JIF			(IRQ_RESERVED + 2)
#define INT_SENSOR				(IRQ_RESERVED + 3)
#define INT_DISPLAY				(IRQ_RESERVED + 4)
#define INT_SPI2					(IRQ_RESERVED + 5)
#define INT_SPI1					(IRQ_RESERVED + 6)
#define INT_ABB					(IRQ_RESERVED + 7)
#define INT_PWM0				(IRQ_RESERVED + 8)
#define INT_GPIO				(IRQ_RESERVED + 9)
#define INT_I2C					(IRQ_RESERVED + 10)
#define INT_KEY_MATRIX		(IRQ_RESERVED + 11)
#define INT_GPT32				(IRQ_RESERVED + 12)
#define INT_LCD_GPIO			(IRQ_RESERVED + 13)
#define INT_SENSOR_GPIO		(IRQ_RESERVED + 14)
#define INT_KEY_GPIO			(IRQ_RESERVED + 15)
#define INT_RFO_GPIO			(IRQ_RESERVED + 16)
#define INT_DSP_JTAG_GPIO		(IRQ_RESERVED + 17)
#define INT_ARM_JTAG_GPIO		(IRQ_RESERVED + 18)
#define INT_SPI_GPIO			(IRQ_RESERVED + 19)
#define INT_I2C_GPIO			(IRQ_RESERVED + 20)
#define INT_PCM_GPIO			(IRQ_RESERVED + 21)
#define INT_AP_UART_DMA		(IRQ_RESERVED + 22)
#define INT_AP_UART_CTL		(IRQ_RESERVED + 23)
#define INT_AUDIO				(IRQ_RESERVED + 24)
#define INT_IRQMM				(IRQ_RESERVED + 25)
#define INT_IRQJOB				(IRQ_RESERVED + 26)
#define INT_IRQGPU				(IRQ_RESERVED + 27)
#define INT_SD1					(IRQ_RESERVED + 28)
#define INT_SD2					(IRQ_RESERVED + 29)
#define INT_USB1				(IRQ_RESERVED + 30)
#define INT_USB2				(IRQ_RESERVED + 31)
#define INT_USB1_WAKEUP		(IRQ_RESERVED + 32)
#define INT_USB2_WAKEUP		(IRQ_RESERVED + 33)
#define INT_ARM7_REPLY		(IRQ_RESERVED + 34)
#define INT_EMMC				(IRQ_RESERVED + 35)
#define INT_NAND				(IRQ_RESERVED + 36)
#define INT_IVPP					(IRQ_RESERVED + 37)
#define INT_SD3					(IRQ_RESERVED + 38)
#define INT_M1DMA				(IRQ_RESERVED + 39)
#define INT_M2DMA				(IRQ_RESERVED + 40)
#define INT_ADSP				(IRQ_RESERVED + 41)
#define INT_AVS					(IRQ_RESERVED + 42)
#define INT_GPT					(IRQ_RESERVED + 43)
#define INT_CA7_CORE0_TIME_UP (IRQ_RESERVED + 44)
#define INT_CA7_CORE1_TIME_UP (IRQ_RESERVED + 45)
#define INT_CA7_CORE2_TIME_UP (IRQ_RESERVED + 46)
#define INT_CA7_CORE3_TIME_UP (IRQ_RESERVED + 47)
#define INT_WDT0				(IRQ_RESERVED + 48)
#define INT_WDT1				(IRQ_RESERVED + 49)
#define INT_WDT2				(IRQ_RESERVED + 50)
#define INT_WDT3				(IRQ_RESERVED + 51)
#define INT_CCI					(IRQ_RESERVED + 52)
#define INT_EFUSE				(IRQ_RESERVED + 53)
#define INT_ARM7_EXPIRE		(IRQ_RESERVED + 54)
#define INT_RESERVED1			(IRQ_RESERVED + 55)
#define INT_RESERVED2			(IRQ_RESERVED + 56)
#define INT_RESERVED3			(IRQ_RESERVED + 57)
#define INT_RESERVED4			(IRQ_RESERVED + 58)
#define INT_RESERVED5			(IRQ_RESERVED + 59)
#define IRQ_END					(IRQ_RESERVED+63)
#define NR_IRQS					(IRQ_END+1)

#endif
