#
# Makefile for the linux kernel.
#

# Object file lists.

obj-$(CONFIG_ARCH_IM9868)		+= im9868-devices.o im9868-timer.o im9868-io.o  im9868-irqs.o

# im9868-gpio.o  im9868-idle.o  im9868-reset.o  im9868-mm.o 

# Board-specific support
obj-$(CONFIG_ARCH_IM9868)		+= board-im9868.o
#obj-$(CONFIG_MACH_RUT100)	+= board-rut1xx.o

